In [1]:
import numpy as np

In [6]:
arr=np.array([1,2,3],np.int64)

In [8]:
arr[0]

np.int64(1)

In [10]:
arr.shape

(3,)

In [11]:
arr.dtype

dtype('int64')

In [16]:
arr1=np.array([[24,35,42],[54,43,67]])
arr1.shape
arr1.dtype

dtype('int64')

In [17]:
arr1[1,2]

np.int64(67)

In [18]:
arr1[1,2]=76

In [19]:
arr1

array([[24, 35, 42],
       [54, 43, 76]])

## Array Creation 1.Conversion from other python structures

In [21]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [22]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
listarray.shape

(3, 3)

In [24]:
listarray.size

9

In [25]:
listarray.dtype

dtype('int64')

In [26]:
listarray[1,2]

np.int64(6)

In [27]:
listarray[1,2]=16

In [28]:
listarray

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8,  9]])

## 2.Using Functions

In [29]:
zeros=np.zeros([2,3])

In [30]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
ones=np.ones([2,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
rng=np.arange(14)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [40]:
lspace=np.linspace([1,10,2])

TypeError: linspace() missing 1 required positional argument: 'stop'

In [45]:
emp=np.empty([4,6])
emp

array([[1.11642488e-311, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 6.95293141e-310, 1.15998412e-028],
       [6.80275364e+199, 1.93307993e+261, 6.21066040e+175,
        6.32677658e+180, 6.82295305e-043, 2.18228540e-094],
       [1.43267083e+161, 2.20832505e-094, 9.29600157e+199,
        1.39029197e-142, 8.30804897e+151, 1.17230825e-047],
       [3.06121843e-057, 2.19467701e-056, 1.22545544e-046,
        5.81587859e+294, 6.17582057e-322, 2.08600674e-308]])

In [47]:
emp_like=np.empty_like(rng)
emp_like

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
identity=np.identity(45)
identity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [51]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [57]:
arr=arr.reshape(3,33)

In [58]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [59]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
arr.shape

(3, 33)

# Numpy Axis

In [64]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [65]:
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.sum(axis=0)
#gives addition of rows

array([12,  8,  9])

In [ ]:
arr.sum(axis=1)
#gives addition of columns

array([ 6, 15,  8])

#Attributes

In [ ]:
arr.T #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [69]:
arr.flat

In [70]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
arr.ndim #no.of dimensions

2

In [72]:
arr.size

9

In [73]:
arr.nbytes

72

In [74]:
one=np.array([1,2,3,4,5])

In [ ]:
one.argmax()
#gives index of largest no.in array
#It is method beause it have ()

np.int64(4)

In [76]:
one.argmin()

np.int64(0)

In [77]:
one.argsort()

array([0, 1, 2, 3, 4])

In [78]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
arr.argmin()

np.int64(8)

In [80]:
arr.argmax()

np.int64(6)

In [81]:
arr.argmax(axis=0)

array([2, 1, 1])

In [82]:
arr.argmax(axis=1)

array([2, 2, 0])

In [83]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [84]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [85]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [86]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [89]:
arr.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [90]:
arr2=np.array([[[1,2,3],[4,5,6],[7,1,0]]])

In [91]:
arr + arr2

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14,  2,  0]]])

In [92]:
arr*arr2

array([[[ 1,  4,  9],
        [16, 25, 36],
        [49,  1,  0]]])

In [93]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [95]:
arr.sum()

np.int64(29)

In [96]:
arr.max()

np.int64(7)

In [ ]:
np.where(arr>5)
#find element and gives tuple

(array([1, 2]), array([2, 0]))

In [98]:
np.count_nonzero(arr)

8

In [99]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [102]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

# Array Slicing

In [103]:
arr[2:3]

array([[7, 1, 0]])

In [104]:
arr[2:]

array([[7, 1, 0]])

In [105]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [108]:
array=np.array([[10,20,40,45],[50,60,70,75],[70,80,90,95]])
array

array([[10, 20, 40, 45],
       [50, 60, 70, 75],
       [70, 80, 90, 95]])

In [109]:
array[1,2:]

array([70, 75])

In [110]:
array[0,0:3]

array([10, 20, 40])

# Attributes of Array

In [111]:
array.shape

(3, 4)

In [112]:
array.size

12

In [113]:
array.ndim

2

In [114]:
array.dtype

dtype('int64')

# Inspecting an Array



In [ ]:
array.shape #Rows and Columns

(3, 4)

In [117]:
len(array)

3

In [119]:
array.size #Total elements

12

In [120]:
array.astype(float)

array([[10., 20., 40., 45.],
       [50., 60., 70., 75.],
       [70., 80., 90., 95.]])

# Mahematical operations and functions on arrays

In [122]:
arr3=np.array([10,20,30,40])
arr4=np.array([50,60,70,80])

In [123]:
arr3+arr4

array([ 60,  80, 100, 120])

In [124]:
np.add(arr3,arr4)

array([ 60,  80, 100, 120])

In [126]:
np.multiply(arr3,arr4)
arr3*arr4

array([ 500, 1200, 2100, 3200])

In [129]:
arr3/arr4
#np.divide(arr3,arr4)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [131]:
#arr3-arr4
np.subtract(arr4,arr3)

array([40, 40, 40, 40])

In [135]:
np.power(arr3,arr4)

array([-5376172055173529600,                    0,                    0,
                          0])

In [136]:
np.sqrt(arr3)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

# Combining and spliting array

In [139]:
np.concatenate((arr3,arr4))

array([10, 20, 30, 40, 50, 60, 70, 80])

In [142]:
np.concatenate((arr3,arr4),axis=0)

array([10, 20, 30, 40, 50, 60, 70, 80])

In [144]:
np.hstack((arr3,arr4))

array([10, 20, 30, 40, 50, 60, 70, 80])

In [145]:
np.vstack((arr3,arr4))

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [146]:
np.array_split(arr3,3)

[array([10, 20]), array([30]), array([40])]

# Adding and removing elements in an array

In [147]:
np.append(arr3,90)

array([10, 20, 30, 40, 90])

In [148]:
np.insert(arr3,1,100)

array([ 10, 100,  20,  30,  40])

In [149]:
np.delete(arr3,[1])

array([10, 30, 40])

# Search,Sort,Filter of arrays

In [157]:
arr0=np.array([[4,3,6,7]])

In [158]:
np.sort(arr0)

array([[3, 4, 6, 7]])

In [159]:
np.where(arr0==4)

(array([0]), array([0]))

In [160]:
np.where(arr0%2==0)

(array([0, 0]), array([0, 2]))

In [161]:
np.searchsorted(arr0,6)

ValueError: object too deep for desired array

In [ ]:
f=[True]# it goes in rowwise

In [169]:
new=arr0[f]
new

array([[4, 3, 6, 7]])

In [173]:
fa=arr0>2

In [174]:
newa=arr0[fa]
newa

array([4, 3, 6, 7])

# Aggregating functions in numpy

In [175]:
np.sum(arr0)

np.int64(20)

In [176]:
np.max(arr0)

np.int64(7)

In [177]:
np.mean(arr0)

np.float64(5.0)

In [178]:
np.cumsum(arr0)

array([ 4,  7, 13, 20])

# Statistical functions in numpy

In [179]:
import statistics as statis

In [181]:
funds=[200,240,320,200,250]
a=np.array(funds)
a

array([200, 240, 320, 200, 250])

In [182]:
np.mean(a)

np.float64(242.0)

In [183]:
np.median(a)

np.float64(240.0)

In [190]:
import statistics as statis
np.mode(a)


AttributeError: module 'numpy' has no attribute 'mode'

In [185]:
np.std(a)

np.float64(44.0)

In [186]:
np.var(a)

np.float64(1936.0)

In [193]:
tobacco_consumtions=[100,230,450]
deaths=[20,40,50]
np.corrcoef(tobacco_consumtions,deaths)

array([[1.        , 0.94358194],
       [0.94358194, 1.        ]])

In [195]:
price=[120,230,340]
sales=[40,30,20]
np.corrcoef(price,sales)

array([[ 1., -1.],
       [-1.,  1.]])